export const commonMsg = {
  usernamePwdIncMsg: "Username or password is incorrect.",
  fillMandatoryField: "Please fill all the mandatory fields.",
  Fname: "Please enter First Name.",
  Lname: "Please enter Last Name.",
  validname: "Please enter valid name it should be alphabets only.",
  validFname: "Please enter valid first name it should be alphabets only.",
  validLname: "Please enter valid last name it should be alphabets only.",
  validPincode: "Please enter valid pincode it should be numbers only.",
  namelength: "Please enter name in between 1 to 50 range.",
  fnamelength: "Please enter First name in between 1 to 50 range.",
  lnamelength: "Please enter Last name in between 1 to 50 range.",
  term: "Please agree to the terms and policies before you submit registration.",
  ragisteredSuccess: "User ragistered sucessfully.",
  validEmail: "Please enter valid Email.",
  userName: "Please enter user name(Email) .",
  registeredUserName: "Please enter registered user name(Email).",
  validUserName: "Plaese enter valid user name(Email).",
  userNameMaxLimit: "User name can not be more than 100 characters.",
  usernameMinLimit: "User name can not be less than 6 characters.",
  email: "Please enter an Email Id.",
  registeredEmail: "Please enter registered Email.",
  emailMaxLimit: "Email can not be more than 100 characters.",
  discountMaxLimit: "Discount code should be from 1 to 50 charasters long.",
  descriptionMaxLimit: "Description can not be more than 5000 characters.",
  emailMinLimit: "Email can not be less than 6 characters.",
  storeReq: "Please enter Store Name.",
  storeMaxLimit: "Store can not be more than 50 characters.",
  storeMinLimit: "Store can not be less than 3 characters.",
  mobile: "Please enter phone number.",
  phone: "Please enter phone number.",
  validPhone: "Please enter valid phone number it should be numbers only.",
  mobileMaxLimit: "Phone number can not be more than 10 characters.",
  mobileMinLimit: "Phone number can not be less than 10 characters.",
  validMobile: "Please enter valid phone number it should be numbers only.",
  psdRstMsg:
    "Your reset password link has been sent to the registered Email Id.",
  fillMandatoryFields: "Please fill all the mandatory fields.",

  password: "Please enter Password.",
  passwordMinLimit: "Password length can contain 6 to 32 characters.",
  passwordMaxLimit: "Password can not be more than 32 characters.",
  passwordmixedValid:
    "Password must have minimum 6 characters, with at least 1 numeric.",

  cnfPassword: "Please enter Confirm Password.",
  cpasswordMinLimit: "Confirm Password length can contain 6 to 32 characters.",
  cpasswordMaxLimit: "Confirm Password can not be more than 32 characters.",
  cpasswordmixedValid:
    "Confirm Password must have minimum 6 characters, with at least 1 numeric.",
  confirmPassword:
    "Password and Confirm Password fields must be identical. Please try again.",

  newPwd: "Please enter New Password.",
  // newPwdMinLimit: "New Password length can contain 6 to 32 characters.",
  // newpwdMaxLimit: "New Password can not be more than 32 characters.",
  // newPasswordValid:
  //   "New Password must have minimum 6 characters, with at least 1 numeric.",

  currentPwd: "Please enter Current password.",
  currentPwdMinLimit: "Current Password length can contain 6 to 32 characters.",
  currentPwdMaxLimit: "Current Password can not be more than 32 characters.",
  currentPwdmixedValid:
    "Current Password must have minimum 6 characters, with at least 1 numeric.",
  oldPwd: "Please enter Current Password.",

  accessTokenExpired: "The access token is expired.",
  alreadyExist: "User already exists.",
  invalidUserName: `You have entered invalid username.`,
  invalidUserId: "Invalid user-id.",
  countryCode: "Please select country code.",
  country: "Please select country.",
  selectGender: "Please select gender.",
  selectDate: "Please enter Date of birth.",
  selectTime: "Please select time.",
  imageSize: "Image can not be more than 4 mb.",
  hobbyError: "Please select on of your hobby.",
  meritalstatusError: "Please select relationship status.",
  educationError: "please select education qualification.",
  pincodeMax: "Pincode must be in 6 digits.",
  pinCodeMin: "Pincode must be in 5 digits.",
  pincodeBlank: "Please enter your city pincode.",
  stateBlank: "Please enter your state name.",
  stateNotvalid: "Please enter valid state name it should be Alphabets only.",
  stateMaxLength: "State can not be more than 50 characters.",
  stateMinLength: "Please enter state in atleast 3 characters.",
  cityBlank: "Please enter City name.",
  cityNotvalid: "Please enter valid city name it should be Alphabets only.",
  addressBlank: "please enter your address.",
  address1: "Please enter the address.",
  address1MaxLimit: "Plaes do not enter more than 50 address length.",
  address1MinLimit: "Address can not be less than 6.",
  address2: "Please enter the address.",
  address2MaxLimit: "Plaes do not enter more than 50 address length.",
  address2MinLimit: "Address can not be less than 3.",
  cityMaxLimit: "City can not be maximum 50.",
  cityMinLimit: "City should not be manimum 3.",
  zipcodeMax: "Zipcode must be in 6 digits.",
  zipcodeMin: "Zipcode must be in 3 digits.",
  zipcodeBlank: "Please enter Pincode.",
  currency: "Please select the currency.",
  currencyMaxLimit: "Currency must be in 3 char.",
  currencyMinLimit: "Currency must be in 3 char.",
  timezone: "Please select the timezone.",
  company: "Company field is required.",
  companymaxlength: "Please enter Company name in between 1 to 50 range.",
  apartmentmaxlength: "Please enter Apartment name in between 1 to 100 range.",
  apartmentRequired: "Apartment, suite, etc. is required.",
  PostalCode: "Postal Code field is required.",
  street: "Please enter the address.",
  street2: "Please enter the address.",
  Name: "Please enter name.",
  InvalidDecimal: "Please enter valid value ex (00.00).",
  InvalidDomain: "Please enter valid domain.",
  InvalidDecimalWeight: "Please enter valid value ex (00.0000).",
  DiscountPercentageValue: "Discount value must be between 0 and 100.",
  SpecificProduct: "Specific products must be added.",
  SpecificCollection: "Specific collections must be added.",
  DiscountCodeRequired: "Discount value can’t be blank.",
  MinimumPurchase: "Minimum purchase can’t be blank.",
  MinimumQuantity: "Minimum quantity can’t be blank.",
  CustomerSegments: "Specific customer segments must be added.",
  SpecificCustomer: "Specific customers must be added.",
  TotalLimit: "Total usage limit can’t be blank.",
  DiscountCode: "Discount code can’t be blank.",
  DiscountTitle: "Title can't be blank.",
  SpecificCountry: "Specific countries must be added.",
  CustomerBuysQuantity: "Quantity for Customer buys can’t be blank.",
  CustomerBuysAmount: "Amount for Customer buys can’t be blank.",
  CustomerGetsQuantity: "Quantity for Customer gets can’t be blank.",
  MaximumUser: "Maximum number of uses per order can’t be blank.",
  validMsg_for_Number: "Please enter valid text it should be Numbers only.",
  Sname: "Please enter Supplier Name.",
  name: "Please enter Name.",
  message: "Please enter message.",
  ApartmentError: "Please enter Apartment name in between 1 to 100 range.",
  CityName: "Please enter City name in between 1 to 50 range.",
  PincodeError: "Please enter Pincode in between 1 to 50 range.",
};

export const demoComponentsMsg = {
  requiredMsg: "This field is required.",
  validMsg_for_Alphabet: "Please enter valid text it should be Alphabets only.",
  validMsg_for_Number: "Please enter valid text it should be Numbers only.",
  lengthMsg_for_Alphabet: "Please enter text in between 1 to 50 range.",
  maxlengthMsg_for_Number: "Plaes do not enter more than 50 numbers.",
  minlengthMsg_for_Number: "Plaes do not enter less than 10 numbers.",
  enterTimeGreterOrEqual:
    "Enter after time must be greater than or equal to current Time.",
  exitTimeGreter: "Exit before time must be greater than to after enter Time.",
  exitDateEqual: "Exit before date must be  equal to enter date.",
  startDateGreterOrEqual:
    "Start date must be greater than or equal to current date.",
  endDateGreterOrEqual: "End date must be greater than or equal to start date.",
  startTime: "Start time must be greater than or equal to current Time.",
  endTime: "End time must be greater than to start Time.",
  validNumber: "Please enter numbers only.",
};
